import { Injectable } from '@angular/core';
import { Departamentos } from '../interfaces/commonsInsterface';


@Injectable({
  providedIn: 'root'
})

export class DepartamentosListService {
  constructor() {}
  departamentos: Departamentos[] = [  
    {  
        id:0,
        departamento:"Amazonas",
        ciudades:[  
            {nombre: "Leticia"},
            {nombre: "Puerto Nari\u00f1o"}
        ]
    },
    {  
        id:1,
        departamento:"Antioquia",
        ciudades:[  
            {nombre: "Abejorral"},
            {nombre: "Abriaqu\u00ed"},
            {nombre: "Alejandr\u00eda"},
            {nombre: "Amag\u00e1"},
            {nombre: "Amalfi"},
            {nombre: "Andes"},
            {nombre: "Angel\u00f3polis"},
            {nombre: "Angostura"},
            {nombre: "Anor\u00ed"},
            {nombre: "Anz\u00e1"},
            {nombre: "Apartad\u00f3"},
            {nombre: "Arboletes"},
            {nombre: "Argelia"},
            {nombre: "Armenia"},
            {nombre: "Barbosa"},
            {nombre: "Bello"},
            {nombre: "Belmira"},
            {nombre: "Betania"},
            {nombre: "Betulia"},
            {nombre: "Brice\u00f1o"},
            {nombre: "Buritic\u00e1"},
            {nombre: "C\u00e1ceres"},
            {nombre: "Caicedo"},
            {nombre: "Caldas"},
            {nombre: "Campamento"},
            {nombre: "Ca\u00f1asgordas"},
            {nombre: "Caracol\u00ed"},
            {nombre: "Caramanta"},
            {nombre: "Carepa"},
            {nombre: "Carolina del Pr\u00edncipe"},
            {nombre: "Caucasia"},
            {nombre: "Chigorod\u00f3"},
            {nombre: "Cisneros"},
            {nombre: "Ciudad Bol\u00edvar"},
            {nombre: "Cocorn\u00e1"},
            {nombre: "Concepci\u00f3n"},
            {nombre: "Concordia"},
            {nombre: "Copacabana"},
            {nombre: "Dabeiba"},
            {nombre: "Donmat\u00edas"},
            {nombre: "Eb\u00e9jico"},
            {nombre: "El Bagre"},
            {nombre: "El Carmen de Viboral"},
            {nombre: "El Pe\u00f1ol"},
            {nombre: "El Retiro"},
            {nombre: "El Santuario"},
            {nombre: "Entrerr\u00edos"},
            {nombre: "Envigado"},
            {nombre: "Fredonia"},
            {nombre: "Frontino"},
            {nombre: "Giraldo"},
            {nombre: "Girardota"},
            {nombre: "G\u00f3mez Plata"},
            {nombre: "Granada"},
            {nombre: "Guadalupe"},
            {nombre: "Guarne"},
            {nombre: "Guatap\u00e9"},
            {nombre: "Heliconia"},
            {nombre: "Hispania"},
            {nombre: "Itag\u00fc\u00ed"},
            {nombre: "Ituango"},
            {nombre: "Jard\u00edn"},
            {nombre: "Jeric\u00f3"},
            {nombre: "La Ceja"},
            {nombre: "La Estrella"},
            {nombre: "La Pintada"},
            {nombre: "La Uni\u00f3n"},
            {nombre: "Liborina"},
            {nombre: "Maceo"},
            {nombre: "Marinilla"},
            {nombre: "Medell\u00edn"},
            {nombre: "Montebello"},
            {nombre: "Murind\u00f3"},
            {nombre: "Mutat\u00e1"},
            {nombre: "Nari\u00f1o"},
            {nombre: "Nech\u00ed"},
            {nombre: "Necocl\u00ed"},
            {nombre: "Olaya"},
            {nombre: "Peque"},
            {nombre: "Pueblorrico"},
            {nombre: "Puerto Berr\u00edo"},
            {nombre: "Puerto Nare"},
            {nombre: "Puerto Triunfo"},
            {nombre: "Remedios"},
            {nombre: "Rionegro"},
            {nombre: "Sabanalarga"},
            {nombre: "Sabaneta"},
            {nombre: "Salgar"},
            {nombre: "San Andr\u00e9s de Cuerquia"},
            {nombre: "San Carlos"},
            {nombre: "San Francisco"},
            {nombre: "San Jer\u00f3nimo"},
            {nombre: "San Jos\u00e9 de la Monta\u00f1a"},
            {nombre: "San Juan de Urab\u00e1"},
            {nombre: "San Luis"},
            {nombre: "San Pedro de Urab\u00e1"},
            {nombre: "San Pedro de los Milagros"},
            {nombre: "San Rafael"},
            {nombre: "San Roque"},
            {nombre: "San Vicente"},
            {nombre: "Santa B\u00e1rbara"},
            {nombre: "Santa Fe de Antioquia"},
            {nombre: "Santa Rosa de Osos"},
            {nombre: "Santo Domingo"},
            {nombre: "Segovia"},
            {nombre: "Sons\u00f3n"},
            {nombre: "Sopetr\u00e1n"},
            {nombre: "T\u00e1mesis"},
            {nombre: "Taraz\u00e1"},
            {nombre: "Tarso"},
            {nombre: "Titirib\u00ed"},
            {nombre: "Toledo"},
            {nombre: "Turbo"},
            {nombre: "Uramita"},
            {nombre: "Urrao"},
            {nombre: "Valdivia"},
            {nombre: "Valpara\u00edso"},
            {nombre: "Vegach\u00ed"},
            {nombre: "Venecia"},
            {nombre: "Vig\u00eda del Fuerte"},
            {nombre: "Yal\u00ed"},
            {nombre: "Yarumal"},
            {nombre: "Yolomb\u00f3"},
            {nombre: "Yond\u00f3"},
            {nombre: "Zaragoza"}
        ]
    },
    {  
        id:2,
        departamento:"Arauca",
        ciudades:[  
            {nombre: "Arauca"},
            {nombre: "Arauquita"},
            {nombre: "Cravo Norte"},
            {nombre: "Fortul"},
            {nombre: "Puerto Rond\u00f3n"},
            {nombre: "Saravena"},
            {nombre: "Tame"}
        ]
    },
    {  
        id:3,
        departamento:"Atl\u00e1ntico",
        ciudades:[  
            {nombre: "Baranoa"},
            {nombre: "Barranquilla"},
            {nombre: "Campo de la Cruz"},
            {nombre: "Candelaria"},
            {nombre: "Galapa"},
            {nombre: "Juan de Acosta"},
            {nombre: "Luruaco"},
            {nombre: "Malambo"},
            {nombre: "Manat\u00ed"},
            {nombre: "Palmar de Varela"},
            {nombre: "Pioj\u00f3"},
            {nombre: "Polonuevo"},
            {nombre: "Ponedera"},
            {nombre: "Puerto Colombia"},
            {nombre: "Repel\u00f3n"},
            {nombre: "Sabanagrande"},
            {nombre: "Sabanalarga"},
            {nombre: "Santa Luc\u00eda"},
            {nombre: "Santo Tom\u00e1s"},
            {nombre: "Soledad"},
            {nombre: "Su\u00e1n"},
            {nombre: "Tubar\u00e1"},
            {nombre: "Usiacur\u00ed"}
        ]
    },
    {  
        id:4,
        departamento:"Bol\u00edvar",
        ciudades:[  
            {nombre: "Ach\u00ed"},
            {nombre: "Altos del Rosario"},
            {nombre: "Arenal"},
            {nombre: "Arjona"},
            {nombre: "Arroyohondo"},
            {nombre: "Barranco de Loba"},
            {nombre: "Brazuelo de Papayal"},
            {nombre: "Calamar"},
            {nombre: "Cantagallo"},
            {nombre: "Cartagena de Indias"},
            {nombre: "Cicuco"},
            {nombre: "Clemencia"},
            {nombre: "C\u00f3rdoba"},
            {nombre: "El Carmen de Bol\u00edvar"},
            {nombre: "El Guamo"},
            {nombre: "El Pe\u00f1\u00f3n"},
            {nombre: "Hatillo de Loba"},
            {nombre: "Magangu\u00e9"},
            {nombre: "Mahates"},
            {nombre: "Margarita"},
            {nombre: "Mar\u00eda la Baja"},
            {nombre: "Momp\u00f3s"},
            {nombre: "Montecristo"},
            {nombre: "Morales"},
            {nombre: "Noros\u00ed"},
            {nombre: "Pinillos"},
            {nombre: "Regidor"},
            {nombre: "R\u00edo Viejo"},
            {nombre: "San Crist\u00f3bal"},
            {nombre: "San Estanislao"},
            {nombre: "San Fernando"},
            {nombre: "San Jacinto del Cauca"},
            {nombre: "San Jacinto"},
            {nombre: "San Juan Nepomuceno"},
            {nombre: "San Mart\u00edn de Loba"},
            {nombre: "San Pablo"},
            {nombre: "Santa Catalina"},
            {nombre: "Santa Rosa"},
            {nombre: "Santa Rosa del Sur"},
            {nombre: "Simit\u00ed"},
            {nombre: "Soplaviento"},
            {nombre: "Talaigua Nuevo"},
            {nombre: "Tiquisio"},
            {nombre: "Turbaco"},
            {nombre: "Turban\u00e1"},
            {nombre: "Villanueva"},
            {nombre: "Zambrano"}
        ]
    },
    {  
        id:5,
        departamento:"Boyac\u00e1",
        ciudades:[  
            {nombre: "Almeida"},
            {nombre: "Aquitania"},
            {nombre: "Arcabuco"},
            {nombre: "Bel\u00e9n"},
            {nombre: "Berbeo"},
            {nombre: "Bet\u00e9itiva"},
            {nombre: "Boavita"},
            {nombre: "Boyac\u00e1"},
            {nombre: "Brice\u00f1o"},
            {nombre: "Buenavista"},
            {nombre: "Busbanz\u00e1"},
            {nombre: "Caldas"},
            {nombre: "Campohermoso"},
            {nombre: "Cerinza"},
            {nombre: "Chinavita"},
            {nombre: "Chiquinquir\u00e1"},
            {nombre: "Ch\u00edquiza"},
            {nombre: "Chiscas"},
            {nombre: "Chita"},
            {nombre: "Chitaraque"},
            {nombre: "Chivat\u00e1"},
            {nombre: "Chivor"},
            {nombre: "Ci\u00e9nega"},
            {nombre: "C\u00f3mbita"},
            {nombre: "Coper"},
            {nombre: "Corrales"},
            {nombre: "Covarach\u00eda"},
            {nombre: "Cubar\u00e1"},
            {nombre: "Cucaita"},
            {nombre: "Cu\u00edtiva"},
            {nombre: "Duitama"},
            {nombre: "El Cocuy"},
            {nombre: "El Espino"},
            {nombre: "Firavitoba"},
            {nombre: "Floresta"},
            {nombre: "Gachantiv\u00e1"},
            {nombre: "G\u00e1meza"},
            {nombre: "Garagoa"},
            {nombre: "Guacamayas"},
            {nombre: "Guateque"},
            {nombre: "Guayat\u00e1"},
            {nombre: "G\u00fcic\u00e1n"},
            {nombre: "Iza"},
            {nombre: "Jenesano"},
            {nombre: "Jeric\u00f3"},
            {nombre: "La Capilla"},
            {nombre: "La Uvita"},
            {nombre: "La Victoria"},
            {nombre: "Labranzagrande"},
            {nombre: "Macanal"},
            {nombre: "Marip\u00ed"},
            {nombre: "Miraflores"},
            {nombre: "Mongua"},
            {nombre: "Mongu\u00ed"},
            {nombre: "Moniquir\u00e1"},
            {nombre: "Motavita"},
            {nombre: "Muzo"},
            {nombre: "Nobsa"},
            {nombre: "Nuevo Col\u00f3n"},
            {nombre: "Oicat\u00e1"},
            {nombre: "Otanche"},
            {nombre: "Pachavita"},
            {nombre: "P\u00e1ez"},
            {nombre: "Paipa"},
            {nombre: "Pajarito"},
            {nombre: "Panqueba"},
            {nombre: "Pauna"},
            {nombre: "Paya"},
            {nombre: "Paz del R\u00edo"},
            {nombre: "Pesca"},
            {nombre: "Pisba"},
            {nombre: "Puerto Boyac\u00e1"},
            {nombre: "Qu\u00edpama"},
            {nombre: "Ramiriqu\u00ed"},
            {nombre: "R\u00e1quira"},
            {nombre: "Rond\u00f3n"},
            {nombre: "Saboy\u00e1"},
            {nombre: "S\u00e1chica"},
            {nombre: "Samac\u00e1"},
            {nombre: "San Eduardo"},
            {nombre: "San Jos\u00e9 de Pare"},
            {nombre: "San Luis de Gaceno"},
            {nombre: "San Mateo"},
            {nombre: "San Miguel de Sema"},
            {nombre: "San Pablo de Borbur"},
            {nombre: "Santa Mar\u00eda"},
            {nombre: "Santa Rosa de Viterbo"},
            {nombre: "Santa Sof\u00eda"},
            {nombre: "Santana"},
            {nombre: "Sativanorte"},
            {nombre: "Sativasur"},
            {nombre: "Siachoque"},
            {nombre: "Soat\u00e1"},
            {nombre: "Socha"},
            {nombre: "Socot\u00e1"},
            {nombre: "Sogamoso"},
            {nombre: "Somondoco"},
            {nombre: "Sora"},
            {nombre: "Sorac\u00e1"},
            {nombre: "Sotaquir\u00e1"},
            {nombre: "Susac\u00f3n"},
            {nombre: "Sutamarch\u00e1n"},
            {nombre: "Sutatenza"},
            {nombre: "Tasco"},
            {nombre: "Tenza"},
            {nombre: "Tiban\u00e1"},
            {nombre: "Tibasosa"},
            {nombre: "Tinjac\u00e1"},
            {nombre: "Tipacoque"},
            {nombre: "Toca"},
            {nombre: "Tog\u00fc\u00ed"},
            {nombre: "T\u00f3paga"},
            {nombre: "Tota"},
            {nombre: "Tunja"},
            {nombre: "Tunungu\u00e1"},
            {nombre: "Turmequ\u00e9"},
            {nombre: "Tuta"},
            {nombre: "Tutaz\u00e1"},
            {nombre: "\u00dambita"},
            {nombre: "Ventaquemada"},
            {nombre: "Villa de Leyva"},
            {nombre: "Viracach\u00e1"},
            {nombre: "Zetaquira"}
        ]
    },
    {  
        id:6,
        departamento:"Caldas",
        ciudades:[  
            {nombre: "Aguadas"},
            {nombre: "Anserma"},
            {nombre: "Aranzazu"},
            {nombre: "Belalc\u00e1zar"},
            {nombre: "Chinchin\u00e1"},
            {nombre: "Filadelfia"},
            {nombre: "La Dorada"},
            {nombre: "La Merced"},
            {nombre: "Manizales"},
            {nombre: "Manzanares"},
            {nombre: "Marmato"},
            {nombre: "Marquetalia"},
            {nombre: "Marulanda"},
            {nombre: "Neira"},
            {nombre: "Norcasia"},
            {nombre: "P\u00e1cora"},
            {nombre: "Palestina"},
            {nombre: "Pensilvania"},
            {nombre: "Riosucio"},
            {nombre: "Risaralda"},
            {nombre: "Salamina"},
            {nombre: "Saman\u00e1"},
            {nombre: "San Jos\u00e9"},
            {nombre: "Sup\u00eda"},
            {nombre: "Victoria"},
            {nombre: "Villamar\u00eda"},
            {nombre: "Viterbo"}
        ]
    },
    {  
        id:7,
        departamento:"Caquet\u00e1",
        ciudades:[  
            {nombre: "Albania"},
            {nombre: "Bel\u00e9n de los Andaqu\u00edes"},
            {nombre: "Cartagena del Chair\u00e1"},
            {nombre: "Curillo"},
            {nombre: "El Doncello"},
            {nombre: "El Paujil"},
            {nombre: "Florencia"},
            {nombre: "La Monta\u00f1ita"},
            {nombre: "Mil\u00e1n"},
            {nombre: "Morelia"},
            {nombre: "Puerto Rico"},
            {nombre: "San Jos\u00e9 del Fragua"},
            {nombre: "San Vicente del Cagu\u00e1n"},
            {nombre: "Solano"},
            {nombre: "Solita"},
            {nombre: "Valpara\u00edso"}
        ]
    },
    {  
        id:8,
        departamento:"Casanare",
        ciudades:[  
            {nombre: "Aguazul"},
            {nombre: "Ch\u00e1meza"},
            {nombre: "Hato Corozal"},
            {nombre: "La Salina"},
            {nombre: "Man\u00ed"},
            {nombre: "Monterrey"},
            {nombre: "Nunch\u00eda"},
            {nombre: "Orocu\u00e9"},
            {nombre: "Paz de Ariporo"},
            {nombre: "Pore"},
            {nombre: "Recetor"},
            {nombre: "Sabanalarga"},
            {nombre: "S\u00e1cama"},
            {nombre: "San Luis de Palenque"},
            {nombre: "T\u00e1mara"},
            {nombre: "Tauramena"},
            {nombre: "Trinidad"},
            {nombre: "Villanueva"},
            {nombre: "Yopal"}
        ]
    },
    {  
        id:9,
        departamento:"Cauca",
        ciudades:[  
            {nombre: "Almaguer"},
            {nombre: "Argelia"},
            {nombre: "Balboa"},
            {nombre: "Bol\u00edvar"},
            {nombre: "Buenos Aires"},
            {nombre: "Cajib\u00edo"},
            {nombre: "Caldono"},
            {nombre: "Caloto"},
            {nombre: "Corinto"},
            {nombre: "El Tambo"},
            {nombre: "Florencia"},
            {nombre: "Guachen\u00e9"},
            {nombre: "Guap\u00ed"},
            {nombre: "Inz\u00e1"},
            {nombre: "Jambal\u00f3"},
            {nombre: "La Sierra"},
            {nombre: "La Vega"},
            {nombre: "L\u00f3pez de Micay"},
            {nombre: "Mercaderes"},
            {nombre: "Miranda"},
            {nombre: "Morales"},
            {nombre: "Padilla"},
            {nombre: "P\u00e1ez"},
            {nombre: "Pat\u00eda"},
            {nombre: "Piamonte"},
            {nombre: "Piendam\u00f3"},
            {nombre: "Popay\u00e1n"},
            {nombre: "Puerto Tejada"},
            {nombre: "Purac\u00e9"},
            {nombre: "Rosas"},
            {nombre: "San Sebasti\u00e1n"},
            {nombre: "Santa Rosa"},
            {nombre: "Santander de Quilichao"},
            {nombre: "Silvia"},
            {nombre: "Sotar\u00e1"},
            {nombre: "Su\u00e1rez"},
            {nombre: "Sucre"},
            {nombre: "Timb\u00edo"},
            {nombre: "Timbiqu\u00ed"},
            {nombre: "Torib\u00edo"},
            {nombre: "Totor\u00f3"},
            {nombre: "Villa Rica"}
        ]
    },
    {  
        id:10,
        departamento:"Cesar",
        ciudades:[  
            {nombre: "Aguachica"},
            {nombre: "Agust\u00edn Codazzi"},
            {nombre: "Astrea"},
            {nombre: "Becerril"},
            {nombre: "Bosconia"},
            {nombre: "Chimichagua"},
            {nombre: "Chiriguan\u00e1"},
            {nombre: "Curuman\u00ed"},
            {nombre: "El Copey"},
            {nombre: "El Paso"},
            {nombre: "Gamarra"},
            {nombre: "Gonz\u00e1lez"},
            {nombre: "La Gloria (Cesar)"},
            {nombre: "La Jagua de Ibirico"},
            {nombre: "La Paz"},
            {nombre: "Manaure Balc\u00f3n del Cesar"},
            {nombre: "Pailitas"},
            {nombre: "Pelaya"},
            {nombre: "Pueblo Bello"},
            {nombre: "R\u00edo de Oro"},
            {nombre: "San Alberto"},
            {nombre: "San Diego"},
            {nombre: "San Mart\u00edn"},
            {nombre: "Tamalameque"},
            {nombre: "Valledupar"}
        ]
    },
    {  
        id:11,
        departamento:"Choc\u00f3",
        ciudades:[  
            {nombre: "Acand\u00ed"},
            {nombre: "Alto Baud\u00f3"},
            {nombre: "Bagad\u00f3"},
            {nombre: "Bah\u00eda Solano"},
            {nombre: "Bajo Baud\u00f3"},
            {nombre: "Bojay\u00e1"},
            {nombre: "Cant\u00f3n de San Pablo"},
            {nombre: "C\u00e9rtegui"},
            {nombre: "Condoto"},
            {nombre: "El Atrato"},
            {nombre: "El Carmen de Atrato"},
            {nombre: "El Carmen del Dari\u00e9n"},
            {nombre: "Istmina"},
            {nombre: "Jurad\u00f3"},
            {nombre: "Litoral de San Juan"},
            {nombre: "Llor\u00f3"},
            {nombre: "Medio Atrato"},
            {nombre: "Medio Baud\u00f3"},
            {nombre: "Medio San Juan"},
            {nombre: "N\u00f3vita"},
            {nombre: "Nuqu\u00ed"},
            {nombre: "Quibd\u00f3"},
            {nombre: "R\u00edo Ir\u00f3"},
            {nombre: "R\u00edo Quito"},
            {nombre: "Riosucio"},
            {nombre: "San Jos\u00e9 del Palmar"},
            {nombre: "Sip\u00ed"},
            {nombre: "Tad\u00f3"},
            {nombre: "Uni\u00f3n Panamericana"},
            {nombre: "Ungu\u00eda"}
        ]
    },
    {  
        id:12,
        departamento:"Cundinamarca",
        ciudades:[  
            {nombre: "Agua de Dios"},
            {nombre: "Alb\u00e1n"},
            {nombre: "Anapoima"},
            {nombre: "Anolaima"},
            {nombre: "Apulo"},
            {nombre: "Arbel\u00e1ez"},
            {nombre: "Beltr\u00e1n"},
            {nombre: "Bituima"},
            {nombre: "Bogot\u00e1"},
            {nombre: "Bojac\u00e1"},
            {nombre: "Cabrera"},
            {nombre: "Cachipay"},
            {nombre: "Cajic\u00e1"},
            {nombre: "Caparrap\u00ed"},
            {nombre: "C\u00e1queza"},
            {nombre: "Carmen de Carupa"},
            {nombre: "Chaguan\u00ed"},
            {nombre: "Ch\u00eda"},
            {nombre: "Chipaque"},
            {nombre: "Choach\u00ed"},
            {nombre: "Chocont\u00e1"},
            {nombre: "Cogua"},
            {nombre: "Cota"},
            {nombre: "Cucunub\u00e1"},
            {nombre: "El Colegio"},
            {nombre: "El Pe\u00f1\u00f3n"},
            {nombre: "El Rosal"},
            {nombre: "Facatativ\u00e1"},
            {nombre: "F\u00f3meque"},
            {nombre: "Fosca"},
            {nombre: "Funza"},
            {nombre: "F\u00faquene"},
            {nombre: "Fusagasug\u00e1"},
            {nombre: "Gachal\u00e1"},
            {nombre: "Gachancip\u00e1"},
            {nombre: "Gachet\u00e1"},
            {nombre: "Gama"},
            {nombre: "Girardot"},
            {nombre: "Granada"},
            {nombre: "Guachet\u00e1"},
            {nombre: "Guaduas"},
            {nombre: "Guasca"},
            {nombre: "Guataqu\u00ed"},
            {nombre: "Guatavita"},
            {nombre: "Guayabal de S\u00edquima"},
            {nombre: "Guayabetal"},
            {nombre: "Guti\u00e9rrez"},
            {nombre: "Jerusal\u00e9n"},
            {nombre: "Jun\u00edn"},
            {nombre: "La Calera"},
            {nombre: "La Mesa"},
            {nombre: "La Palma"},
            {nombre: "La Pe\u00f1a"},
            {nombre: "La Vega"},
            {nombre: "Lenguazaque"},
            {nombre: "Machet\u00e1"},
            {nombre: "Madrid"},
            {nombre: "Manta"},
            {nombre: "Medina"},
            {nombre: "Mosquera"},
            {nombre: "Nari\u00f1o"},
            {nombre: "Nemoc\u00f3n"},
            {nombre: "Nilo"},
            {nombre: "Nimaima"},
            {nombre: "Nocaima"},
            {nombre: "Pacho"},
            {nombre: "Paime"},
            {nombre: "Pandi"},
            {nombre: "Paratebueno"},
            {nombre: "Pasca"},
            {nombre: "Puerto Salgar"},
            {nombre: "Pul\u00ed"},
            {nombre: "Quebradanegra"},
            {nombre: "Quetame"},
            {nombre: "Quipile"},
            {nombre: "Ricaurte"},
            {nombre: "San Antonio del Tequendama"},
            {nombre: "San Bernardo"},
            {nombre: "San Cayetano"},
            {nombre: "San Francisco"},
            {nombre: "San Juan de Rioseco"},
            {nombre: "Sasaima"},
            {nombre: "Sesquil\u00e9"},
            {nombre: "Sibat\u00e9"},
            {nombre: "Silvania"},
            {nombre: "Simijaca"},
            {nombre: "Soacha"},
            {nombre: "Sop\u00f3"},
            {nombre: "Subachoque"},
            {nombre: "Suesca"},
            {nombre: "Supat\u00e1"},
            {nombre: "Susa"},
            {nombre: "Sutatausa"},
            {nombre: "Tabio"},
            {nombre: "Tausa"},
            {nombre: "Tena"},
            {nombre: "Tenjo"},
            {nombre: "Tibacuy"},
            {nombre: "Tibirita"},
            {nombre: "Tocaima"},
            {nombre: "Tocancip\u00e1"},
            {nombre: "Topaip\u00ed"},
            {nombre: "Ubal\u00e1"},
            {nombre: "Ubaque"},
            {nombre: "Ubat\u00e9"},
            {nombre: "Une"},
            {nombre: "\u00datica"},
            {nombre: "Venecia"},
            {nombre: "Vergara"},
            {nombre: "Vian\u00ed"},
            {nombre: "Villag\u00f3mez"},
            {nombre: "Villapinz\u00f3n"},
            {nombre: "Villeta"},
            {nombre: "Viot\u00e1"},
            {nombre: "Yacop\u00ed"},
            {nombre: "Zipac\u00f3n"},
            {nombre: "Zipaquir\u00e1"}
        ]
    },
    {  
        id:13,
        departamento:"C\u00f3rdoba",
        ciudades:[  
            {nombre: "Ayapel"},
            {nombre: "Buenavista"},
            {nombre: "Canalete"},
            {nombre: "Ceret\u00e9"},
            {nombre: "Chim\u00e1"},
            {nombre: "Chin\u00fa"},
            {nombre: "Ci\u00e9naga de Oro"},
            {nombre: "Cotorra"},
            {nombre: "La Apartada"},
            {nombre: "Lorica"},
            {nombre: "Los C\u00f3rdobas"},
            {nombre: "Momil"},
            {nombre: "Montel\u00edbano"},
            {nombre: "Monter\u00eda"},
            {nombre: "Mo\u00f1itos"},
            {nombre: "Planeta Rica"},
            {nombre: "Pueblo Nuevo"},
            {nombre: "Puerto Escondido"},
            {nombre: "Puerto Libertador"},
            {nombre: "Pur\u00edsima"},
            {nombre: "Sahag\u00fan"},
            {nombre: "San Andr\u00e9s de Sotavento"},
            {nombre: "San Antero"},
            {nombre: "San Bernardo del Viento"},
            {nombre: "San Carlos"},
            {nombre: "San Jos\u00e9 de Ur\u00e9"},
            {nombre: "San Pelayo"},
            {nombre: "Tierralta"},
            {nombre: "Tuch\u00edn"},
            {nombre: "Valencia"}
        ]
    },
    {  
        id:14,
        departamento:"Guain\u00eda",
        ciudades:[  
            {nombre: "In\u00edrida"}
        ]
    },
    {  
        id:15,
        departamento:"Guaviare",
        ciudades:[  
            {nombre: "Calamar"},
            {nombre: "El Retorno"},
            {nombre: "Miraflores"},
            {nombre: "San Jos\u00e9 del Guaviare"}
        ]
    },
    {  
        id:16,
        departamento:"Huila",
        ciudades:[  
            {nombre: "Acevedo"},
            {nombre: "Agrado"},
            {nombre: "Aipe"},
            {nombre: "Algeciras"},
            {nombre: "Altamira"},
            {nombre: "Baraya"},
            {nombre: "Campoalegre"},
            {nombre: "Colombia"},
            {nombre: "El Pital"},
            {nombre: "El\u00edas"},
            {nombre: "Garz\u00f3n"},
            {nombre: "Gigante"},
            {nombre: "Guadalupe"},
            {nombre: "Hobo"},
            {nombre: "\u00cdquira"},
            {nombre: "Isnos"},
            {nombre: "La Argentina"},
            {nombre: "La Plata"},
            {nombre: "N\u00e1taga"},
            {nombre: "Neiva"},
            {nombre: "Oporapa"},
            {nombre: "Paicol"},
            {nombre: "Palermo"},
            {nombre: "Palestina"},
            {nombre: "Pitalito"},
            {nombre: "Rivera"},
            {nombre: "Saladoblanco"},
            {nombre: "San Agust\u00edn"},
            {nombre: "Santa Mar\u00eda"},
            {nombre: "Suaza"},
            {nombre: "Tarqui"},
            {nombre: "Tello"},
            {nombre: "Teruel"},
            {nombre: "Tesalia"},
            {nombre: "Timan\u00e1"},
            {nombre: "Villavieja"},
            {nombre: "Yaguar\u00e1"}
        ]
    },
    {  
        id:17,
        departamento:"La Guajira",
        ciudades:[  
            {nombre: "Albania"},
            {nombre: "Barrancas"},
            {nombre: "Dibulla"},
            {nombre: "Distracci\u00f3n"},
            {nombre: "El Molino"},
            {nombre: "Fonseca"},
            {nombre: "Hatonuevo"},
            {nombre: "La Jagua del Pilar"},
            {nombre: "Maicao"},
            {nombre: "Manaure"},
            {nombre: "Riohacha"},
            {nombre: "San Juan del Cesar"},
            {nombre: "Uribia"},
            {nombre: "Urumita"},
            {nombre: "Villanueva"}
        ]
    },
    {  
        id:18,
        departamento:"Magdalena",
        ciudades:[  
            {nombre: "Algarrobo"},
            {nombre: "Aracataca"},
            {nombre: "Ariguan\u00ed"},
            {nombre: "Cerro de San Antonio"},
            {nombre: "Chibolo"},
            {nombre: "Chibolo"},
            {nombre: "Ci\u00e9naga"},
            {nombre: "Concordia"},
            {nombre: "El Banco"},
            {nombre: "El Pi\u00f1\u00f3n"},
            {nombre: "El Ret\u00e9n"},
            {nombre: "Fundaci\u00f3n"},
            {nombre: "Guamal"},
            {nombre: "Nueva Granada"},
            {nombre: "Pedraza"},
            {nombre: "Piji\u00f1o del Carmen"},
            {nombre: "Pivijay"},
            {nombre: "Plato"},
            {nombre: "Pueblo Viejo"},
            {nombre: "Remolino"},
            {nombre: "Sabanas de San \u00c1ngel"},
            {nombre: "Salamina"},
            {nombre: "San Sebasti\u00e1n de Buenavista"},
            {nombre: "San Zen\u00f3n"},
            {nombre: "Santa Ana"},
            {nombre: "Santa B\u00e1rbara de Pinto"},
            {nombre: "Santa Marta"},
            {nombre: "Sitionuevo"},
            {nombre: "Tenerife"},
            {nombre: "Zapay\u00e1n"},
            {nombre: "Zona Bananera"}
        ]
    },
    {  
        id:19,
        departamento:"Meta",
        ciudades:[  
            {nombre: "Acac\u00edas"},
            {nombre: "Barranca de Up\u00eda"},
            {nombre: "Cabuyaro"},
            {nombre: "Castilla la Nueva"},
            {nombre: "Cubarral"},
            {nombre: "Cumaral"},
            {nombre: "El Calvario"},
            {nombre: "El Castillo"},
            {nombre: "El Dorado"},
            {nombre: "Fuente de Oro"},
            {nombre: "Granada"},
            {nombre: "Guamal"},
            {nombre: "La Macarena"},
            {nombre: "La Uribe"},
            {nombre: "Lejan\u00edas"},
            {nombre: "Mapirip\u00e1n"},
            {nombre: "Mesetas"},
            {nombre: "Puerto Concordia"},
            {nombre: "Puerto Gait\u00e1n"},
            {nombre: "Puerto Lleras"},
            {nombre: "Puerto L\u00f3pez"},
            {nombre: "Puerto Rico"},
            {nombre: "Restrepo"},
            {nombre: "San Carlos de Guaroa"},
            {nombre: "San Juan de Arama"},
            {nombre: "San Juanito"},
            {nombre: "San Mart\u00edn"},
            {nombre: "Villavicencio"},
            {nombre: "Vista Hermosa"}
        ]
    },
    {  
        id:20,
        departamento:"Nari\u00f1o",
        ciudades:[  
            {nombre: "Aldana"},
            {nombre: "Ancuy\u00e1"},
            {nombre: "Arboleda"},
            {nombre: "Barbacoas"},
            {nombre: "Bel\u00e9n"},
            {nombre: "Buesaco"},
            {nombre: "Chachag\u00fc\u00ed"},
            {nombre: "Col\u00f3n"},
            {nombre: "Consac\u00e1"},
            {nombre: "Contadero"},
            {nombre: "C\u00f3rdoba"},
            {nombre: "Cuaspud"},
            {nombre: "Cumbal"},
            {nombre: "Cumbitara"},
            {nombre: "El Charco"},
            {nombre: "El Pe\u00f1ol"},
            {nombre: "El Rosario"},
            {nombre: "El Tabl\u00f3n"},
            {nombre: "El Tambo"},
            {nombre: "Francisco Pizarro"},
            {nombre: "Funes"},
            {nombre: "Guachucal"},
            {nombre: "Guaitarilla"},
            {nombre: "Gualmat\u00e1n"},
            {nombre: "Iles"},
            {nombre: "Imu\u00e9s"},
            {nombre: "Ipiales"},
            {nombre: "La Cruz"},
            {nombre: "La Florida"},
            {nombre: "La Llanada"},
            {nombre: "La Tola"},
            {nombre: "La Uni\u00f3n"},
            {nombre: "Leiva"},
            {nombre: "Linares"},
            {nombre: "Los Andes"},
            {nombre: "Mag\u00fc\u00ed Pay\u00e1n"},
            {nombre: "Mallama"},
            {nombre: "Mosquera"},
            {nombre: "Nari\u00f1o"},
            {nombre: "Olaya Herrera"},
            {nombre: "Ospina"},
            {nombre: "Pasto"},
            {nombre: "Policarpa"},
            {nombre: "Potos\u00ed"},
            {nombre: "Providencia"},
            {nombre: "Puerres"},
            {nombre: "Pupiales"},
            {nombre: "Ricaurte"},
            {nombre: "Roberto Pay\u00e1n"},
            {nombre: "Samaniego"},
            {nombre: "San Bernardo"},
            {nombre: "San Jos\u00e9 de Alb\u00e1n"},
            {nombre: "San Lorenzo"},
            {nombre: "San Pablo"},
            {nombre: "San Pedro de Cartago"},
            {nombre: "Sandon\u00e1"},
            {nombre: "Santa B\u00e1rbara"},
            {nombre: "Santacruz"},
            {nombre: "Sapuyes"},
            {nombre: "Taminango"},
            {nombre: "Tangua"},
            {nombre: "Tumaco"},
            {nombre: "T\u00faquerres"},
            {nombre: "Yacuanquer"}
        ]
    },
    {  
        id:21,
        departamento:"Norte de Santander",
        ciudades:[  
            {nombre: "\u00c1brego"},
            {nombre: "Arboledas"},
            {nombre: "Bochalema"},
            {nombre: "Bucarasica"},
            {nombre: "C\u00e1chira"},
            {nombre: "C\u00e1cota"},
            {nombre: "Chin\u00e1cota"},
            {nombre: "Chitag\u00e1"},
            {nombre: "Convenci\u00f3n"},
            {nombre: "C\u00facuta"},
            {nombre: "Cucutilla"},
            {nombre: "Duran\u00eda"},
            {nombre: "El Carmen"},
            {nombre: "El Tarra"},
            {nombre: "El Zulia"},
            {nombre: "Gramalote"},
            {nombre: "Hacar\u00ed"},
            {nombre: "Herr\u00e1n"},
            {nombre: "La Esperanza"},
            {nombre: "La Playa de Bel\u00e9n"},
            {nombre: "Labateca"},
            {nombre: "Los Patios"},
            {nombre: "Lourdes"},
            {nombre: "Mutiscua"},
            {nombre: "Oca\u00f1a"},
            {nombre: "Pamplona"},
            {nombre: "Pamplonita"},
            {nombre: "Puerto Santander"},
            {nombre: "Ragonvalia"},
            {nombre: "Salazar de Las Palmas"},
            {nombre: "San Calixto"},
            {nombre: "San Cayetano"},
            {nombre: "Santiago"},
            {nombre: "Santo Domingo de Silos"},
            {nombre: "Sardinata"},
            {nombre: "Teorama"},
            {nombre: "Tib\u00fa"},
            {nombre: "Toledo"},
            {nombre: "Villa Caro"},
            {nombre: "Villa del Rosario"}
        ]
    },
    {  
        id:22,
        departamento:"Putumayo",
        ciudades:[  
            {nombre: "Col\u00f3n"},
            {nombre: "Mocoa"},
            {nombre: "Orito"},
            {nombre: "Puerto As\u00eds"},
            {nombre: "Puerto Caicedo"},
            {nombre: "Puerto Guzm\u00e1n"},
            {nombre: "Puerto Legu\u00edzamo"},
            {nombre: "San Francisco"},
            {nombre: "San Miguel"},
            {nombre: "Santiago"},
            {nombre: "Sibundoy"},
            {nombre: "Valle del Guamuez"},
            {nombre: "Villagarz\u00f3n"}
        ]
    },
    {  
        id:23,
        departamento:"Quind\u00edo",
        ciudades:[  
            {nombre: "Armenia"},
            {nombre: "Buenavista"},
            {nombre: "Calarc\u00e1"},
            {nombre: "Circasia"},
            {nombre: "C\u00f3rdoba"},
            {nombre: "Filandia"},
            {nombre: "G\u00e9nova"},
            {nombre: "La Tebaida"},
            {nombre: "Montenegro"},
            {nombre: "Pijao"},
            {nombre: "Quimbaya"},
            {nombre: "Salento"}
        ]
    },
    {  
        id:24,
        departamento:"Risaralda",
        ciudades:[  
            {nombre: "Ap\u00eda"},
            {nombre: "Balboa"},
            {nombre: "Bel\u00e9n de Umbr\u00eda"},
            {nombre: "Dosquebradas"},
            {nombre: "Gu\u00e1tica"},
            {nombre: "La Celia"},
            {nombre: "La Virginia"},
            {nombre: "Marsella"},
            {nombre: "Mistrat\u00f3"},
            {nombre: "Pereira"},
            {nombre: "Pueblo Rico"},
            {nombre: "Quinch\u00eda"},
            {nombre: "Santa Rosa de Cabal"},
            {nombre: "Santuario"}
        ]
    },
    {  
        id:25,
        departamento:"San Andr\u00e9s y Providencia",
        ciudades:[  
            {nombre: "Providencia y Santa Catalina Islas"},
            {nombre: "San Andr\u00e9s"}
        ]
    },
    {  
        id:26,
        departamento:"Santander",
        ciudades:[  
            {nombre: "Aguada"},
            {nombre: "Albania"},
            {nombre: "Aratoca"},
            {nombre: "Barbosa"},
            {nombre: "Barichara"},
            {nombre: "Barrancabermeja"},
            {nombre: "Betulia"},
            {nombre: "Bol\u00edvar"},
            {nombre: "Bucaramanga"},
            {nombre: "Cabrera"},
            {nombre: "California"},
            {nombre: "Capitanejo"},
            {nombre: "Carcas\u00ed"},
            {nombre: "Cepit\u00e1"},
            {nombre: "Cerrito"},
            {nombre: "Charal\u00e1"},
            {nombre: "Charta"},
            {nombre: "Chima"},
            {nombre: "Chipat\u00e1"},
            {nombre: "Cimitarra"},
            {nombre: "Concepci\u00f3n"},
            {nombre: "Confines"},
            {nombre: "Contrataci\u00f3n"},
            {nombre: "Coromoro"},
            {nombre: "Curit\u00ed"},
            {nombre: "El Carmen de Chucur\u00ed"},
            {nombre: "El Guacamayo"},
            {nombre: "El Pe\u00f1\u00f3n"},
            {nombre: "El Play\u00f3n"},
            {nombre: "El Socorro"},
            {nombre: "Encino"},
            {nombre: "Enciso"},
            {nombre: "Flori\u00e1n"},
            {nombre: "Floridablanca"},
            {nombre: "Gal\u00e1n"},
            {nombre: "G\u00e1mbita"},
            {nombre: "Gir\u00f3n"},
            {nombre: "Guaca"},
            {nombre: "Guadalupe"},
            {nombre: "Guapot\u00e1"},
            {nombre: "Guavat\u00e1"},
            {nombre: "G\u00fcepsa"},
            {nombre: "Hato"},
            {nombre: "Jes\u00fas Mar\u00eda"},
            {nombre: "Jord\u00e1n"},
            {nombre: "La Belleza"},
            {nombre: "La Paz"},
            {nombre: "Land\u00e1zuri"},
            {nombre: "Lebrija"},
            {nombre: "Los Santos"},
            {nombre: "Macaravita"},
            {nombre: "M\u00e1laga"},
            {nombre: "Matanza"},
            {nombre: "Mogotes"},
            {nombre: "Molagavita"},
            {nombre: "Ocamonte"},
            {nombre: "Oiba"},
            {nombre: "Onzaga"},
            {nombre: "Palmar"},
            {nombre: "Palmas del Socorro"},
            {nombre: "P\u00e1ramo"},
            {nombre: "Piedecuesta"},
            {nombre: "Pinchote"},
            {nombre: "Puente Nacional"},
            {nombre: "Puerto Parra"},
            {nombre: "Puerto Wilches"},
            {nombre: "Rionegro"},
            {nombre: "Sabana de Torres"},
            {nombre: "San Andr\u00e9s"},
            {nombre: "San Benito"},
            {nombre: "San Gil"},
            {nombre: "San Joaqu\u00edn"},
            {nombre: "San Jos\u00e9 de Miranda"},
            {nombre: "San Miguel"},
            {nombre: "San Vicente de Chucur\u00ed"},
            {nombre: "Santa B\u00e1rbara"},
            {nombre: "Santa Helena del Op\u00f3n"},
            {nombre: "Simacota"},
            {nombre: "Suaita"},
            {nombre: "Sucre"},
            {nombre: "Surat\u00e1"},
            {nombre: "Tona"},
            {nombre: "Valle de San Jos\u00e9"},
            {nombre: "V\u00e9lez"},
            {nombre: "Vetas"},
            {nombre: "Villanueva"},
            {nombre: "Zapatoca"}
        ]
    },
    {  
        id:27,
        departamento:"Sucre",
        ciudades:[  
            {nombre: "Buenavista"},
            {nombre: "Caimito"},
            {nombre: "Chal\u00e1n"},
            {nombre: "Colos\u00f3"},
            {nombre: "Corozal"},
            {nombre: "Cove\u00f1as"},
            {nombre: "El Roble"},
            {nombre: "Galeras"},
            {nombre: "Guaranda"},
            {nombre: "La Uni\u00f3n"},
            {nombre: "Los Palmitos"},
            {nombre: "Majagual"},
            {nombre: "Morroa"},
            {nombre: "Ovejas"},
            {nombre: "Sampu\u00e9s"},
            {nombre: "San Antonio de Palmito"},
            {nombre: "San Benito Abad"},
            {nombre: "San Juan de Betulia"},
            {nombre: "San Marcos"},
            {nombre: "San Onofre"},
            {nombre: "San Pedro"},
            {nombre: "Sinc\u00e9"},
            {nombre: "Sincelejo"},
            {nombre: "Sucre"},
            {nombre: "Tol\u00fa"},
            {nombre: "Tol\u00fa Viejo"}
        ]
    },
    {  
        id:28,
        departamento:"Tolima",
        ciudades:[  
            {nombre: "Alpujarra"},
            {nombre: "Alvarado"},
            {nombre: "Ambalema"},
            {nombre: "Anzo\u00e1tegui"},
            {nombre: "Armero"},
            {nombre: "Ataco"},
            {nombre: "Cajamarca"},
            {nombre: "Carmen de Apical\u00e1"},
            {nombre: "Casabianca"},
            {nombre: "Chaparral"},
            {nombre: "Coello"},
            {nombre: "Coyaima"},
            {nombre: "Cunday"},
            {nombre: "Dolores"},
            {nombre: "El Espinal"},
            {nombre: "Fal\u00e1n"},
            {nombre: "Flandes"},
            {nombre: "Fresno"},
            {nombre: "Guamo"},
            {nombre: "Herveo"},
            {nombre: "Honda"},
            {nombre: "Ibagu\u00e9"},
            {nombre: "Icononzo"},
            {nombre: "L\u00e9rida"},
            {nombre: "L\u00edbano"},
            {nombre: "Mariquita"},
            {nombre: "Melgar"},
            {nombre: "Murillo"},
            {nombre: "Natagaima"},
            {nombre: "Ortega"},
            {nombre: "Palocabildo"},
            {nombre: "Piedras"},
            {nombre: "Planadas"},
            {nombre: "Prado"},
            {nombre: "Purificaci\u00f3n"},
            {nombre: "Rioblanco"},
            {nombre: "Roncesvalles"},
            {nombre: "Rovira"},
            {nombre: "Salda\u00f1a"},
            {nombre: "San Antonio"},
            {nombre: "San Luis"},
            {nombre: "Santa Isabel"},
            {nombre: "Su\u00e1rez"},
            {nombre: "Valle de San Juan"},
            {nombre: "Venadillo"},
            {nombre: "Villahermosa"},
            {nombre: "Villarrica"}
        ]
    },
    {  
        id:29,
        departamento:"Valle del Cauca",
        ciudades:[  
            {nombre: "Alcal\u00e1"},
            {nombre: "Andaluc\u00eda"},
            {nombre: "Ansermanuevo"},
            {nombre: "Argelia"},
            {nombre: "Bol\u00edvar"},
            {nombre: "Buenaventura"},
            {nombre: "Buga"},
            {nombre: "Bugalagrande"},
            {nombre: "Caicedonia"},
            {nombre: "Cali"},
            {nombre: "Calima"},
            {nombre: "Candelaria"},
            {nombre: "Cartago"},
            {nombre: "Dagua"},
            {nombre: "El \u00c1guila"},
            {nombre: "El Cairo"},
            {nombre: "El Cerrito"},
            {nombre: "El Dovio"},
            {nombre: "Florida"},
            {nombre: "Ginebra"},
            {nombre: "Guacar\u00ed"},
            {nombre: "Jamund\u00ed"},
            {nombre: "La Cumbre"},
            {nombre: "La Uni\u00f3n"},
            {nombre: "La Victoria"},
            {nombre: "Obando"},
            {nombre: "Palmira"},
            {nombre: "Pradera"},
            {nombre: "Restrepo"},
            {nombre: "Riofr\u00edo"},
            {nombre: "Roldanillo"},
            {nombre: "San Pedro"},
            {nombre: "Sevilla"},
            {nombre: "Toro"},
            {nombre: "Trujillo"},
            {nombre: "Tulu\u00e1"},
            {nombre: "Ulloa"},
            {nombre: "Versalles"},
            {nombre: "Vijes"},
            {nombre: "Yotoco"},
            {nombre: "Yumbo"},
            {nombre: "Zarzal"}
        ]
    },
    {  
        id:30,
        departamento:"Vaup\u00e9s",
        ciudades:[  
            {nombre: "Carur\u00fa"},
            {nombre: "Mit\u00fa"},
            {nombre: "Taraira"}
        ]
    },
    {  
        id:31,
        departamento:"Vichada",
        ciudades:[  
            {nombre: "Cumaribo"},
            {nombre: "La Primavera"},
            {nombre: "Puerto Carre\u00f1o"},
            {nombre: "Santa Rosal\u00eda"}
        ]
    }
]
}
